using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MML.Enterprise.Common.Mapping;

namespace MML.Enterprise.Common.DataFile
{
    /// <summary>
    /// Data file transformers are responsible for the application of a particular mapping to either a data stream or a file.
    /// It should be able to use that mapping to both generate whatever file format output is required, as well as parse files in that format.
    /// Generally transformers will act on mappings generated by a Mapping Generator for the same file type.
    /// </summary>
    public interface IDataFileTransformer
    {       
        Stream TransformToFile(Mapping.Mapping mapping, IList<Dictionary<string, object>> data, IDictionary<string, object> parameters = null);
        Stream TransformToFile(IList data, IList<string> properties = null);

        Dictionary<string, object> TransformFromFile(string mapping, Stream file);
        Dictionary<string, object> TransformFromFile(Mapping.Mapping mapping, Stream file);

        IList<T> TransformFromFile<T>(Mapping.Mapping mapping, Stream file);

    }
}
